### PR TITLE
Fix Create Connector actions parsing

### LINKED ISSUE #123: [BUG] TypeCast issue for Create Connector
### What is the bug?
When invoking create connector workflow step using execute API it fails with the below
```
[2023-10-30T20:35:21,118][ERROR][o.o.f.t.ProvisionWorkflowTransportAction] [ip-172-31-56-214] Provisioning failed for workflow wG5LgosB1lilWaNu-qh2 : org.opensearch.flowframework.exception.FlowFrameworkException: java.lang.ClassCastException: class [Ljava.util.Map; cannot be cast to class java.util.List ([Ljava.util.Map; and java.util.List are in module java.base of loader 'bootstrap')
```

The issue on casting the content object to `List<ConnectorActions>` [here](https://github.com/opensearch-project/opensearch-ai-flow-framework/blob/main/src/main/java/org/opensearch/flowframework/workflow/CreateConnectorStep.java#L115).

### How can one reproduce the bug?
1. Run OS cluster with ml-commons and flow-framework plugin installed.
2. Hit the execute API
```
curl -XPOST --insecure -u 'admin:admin' -H "Content-Type: application/json" 'http://localhost:9200/_plugins/_flow_framework/workflow' -d '{"name":"deploy-register-model","description":"test case","use_case":"SEMANTIC_SEARCH","version":{"template":"1.0.0","compatibility":["2.12.0","3.0.0"]},"workflows":{"provision":{"nodes":[{"id":"workflow_step_1","type":"create_connector","inputs":{"name":"OpenAI Chat Connector","description":"The connector to public OpenAI model service for GPT 3.5","version":"1","protocol":"http","parameters":{"endpoint":"api.openai.com","model":"gpt-3.5-turbo"},"credential":{"openAI_key":"..."},"actions":[{"action_type":"predict","method":"POST","url":"https://${parameters.endpoint}/v1/chat/completions"}]}},{"id":"workflow_step_2","type":"deploy_model","inputs":{"model_id":{}}}],"edges":[{"source":"workflow_step_1","dest":"workflow_step_2"}]}}}'
```
3. Invoke the provision API:
```
curl -XPOST --insecure -u 'admin:admin' -H "Content-Type: application/json" 'http://localhost:9200/_plugins/_flow_framework/workflow/<workflow ID from previous step>/_provision'
```

### What is the expected behavior?
A connector should be created.

### What is your host/environment?
Ubuntu

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

Properly parses the actions in a Create Connector step

### Issues Resolved

Fixes #123 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/test/java/org/opensearch/flowframework/workflow/CreateConnectorStepTests.java [hunk 1]
```diff
@@ -59,30 +64,17 @@ public void setUp() throws Exception {
                 Map.entry("protocol", "test"),
                 Map.entry("params", params),
```
Comment (dbwiddis) [inline src/test/java/org/opensearch/flowframework/workflow/CreateConnectorStepTests.java:65]: Note to reviewers: this is missing test coverage because the key "params" here doesn't match the `PARAMETERS_FIELD` String value, implied by the replaced strings in the ConnectorAction request body.  Should this be "parameters"?  If so I'll fix it.

**Review by owaiskazi19 — APPROVED** [review]
Thanks for fixing this! For later: we should also handle the parsing of PROCESSORS_FIELD of ingest pipeline in CreatePipelineStep.java.

**Review by joshpalis — APPROVED** [review]
